from enum import Enum


class TaskStatus(str, Enum):
    CREATED = "CREATED"
    PREVIEWING = "PREVIEWING"
    #PLANNING = "PLANNING"
    WAITING_CONFIRM = "WAITING_CONFIRM"
    CONFIRMED = "CONFIRMED"

    # 新增：确认后进入队列，等待 worker 领取
    QUEUED = "QUEUED"

    RUNNING = "RUNNING"

    WAITING_USER_INPUT = "WAITING_USER_INPUT"

    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    IGNORED = "IGNORED"

    PLANNING = "PLANNING"

    DOC_GENERATING = "DOC_GENERATING"
    DOC_READY = "DOC_READY"
    SLIDE_GENERATING = "SLIDE_GENERATING"
    SLIDE_READY = "SLIDE_READY"
    DELIVERING = "DELIVERING"
    DELIVERED = "DELIVERED"


class TaskType(str, Enum):
    UNKNOWN = "UNKNOWN"
    CREATE_DOC_FROM_IM = "CREATE_DOC_FROM_IM"
    GENERATE_SLIDES = "GENERATE_SLIDES"
    IM_TO_DOC_TO_PPT = "IM_TO_DOC_TO_PPT"
    SUMMARIZE_DISCUSSION = "SUMMARIZE_DISCUSSION"


class TaskSourceType(str, Enum):
    FEISHU_IM = "FEISHU_IM"
    WEB_WORKBENCH = "WEB_WORKBENCH"

class AgentActionStatus(str, Enum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"

class TaskJobType(str, Enum):
    RUN_LANGGRAPH = "RUN_LANGGRAPH"

class TaskJobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    CANCELLED = "CANCELLED"