from enum import StrEnum


class TaskStatus(StrEnum):
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    WAITING_CONFIRM = "WAITING_CONFIRM"
    RUNNING = "RUNNING"
    DOC_GENERATING = "DOC_GENERATING"
    SLIDE_GENERATING = "SLIDE_GENERATING"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"