from enum import Enum


class TaskStatus(str, Enum):
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    WAITING_CONFIRM = "WAITING_CONFIRM"
    RUNNING = "RUNNING"
    DOC_GENERATING = "DOC_GENERATING"
    DOC_READY = "DOC_READY"
    SLIDE_GENERATING = "SLIDE_GENERATING"
    SLIDE_READY = "SLIDE_READY"
    DELIVERING = "DELIVERING"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskType(str, Enum):
    UNKNOWN = "UNKNOWN"
    CREATE_DOC_FROM_IM = "CREATE_DOC_FROM_IM"
    GENERATE_SLIDES = "GENERATE_SLIDES"
    IM_TO_DOC_TO_PPT = "IM_TO_DOC_TO_PPT"
    SUMMARIZE_DISCUSSION = "SUMMARIZE_DISCUSSION"


class TaskSourceType(str, Enum):
    FEISHU_IM = "FEISHU_IM"
    WEB_WORKBENCH = "WEB_WORKBENCH"